[project]
name = "schoolLib"
version = "0.0.1"
description = "A simple school library"
authors = [
    {name = "Stephen Gaito", email = "stephen@perceptisys.co.uk"},
]
dependencies = [
    "starlette[full]>=0.37.2",
    "uvicorn>=0.30.1",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[project.scripts]
schoolLib = "schoolLib.cli:cli"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
