#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the Simple School Library command anywhere in a user's
# workspace.

createWebServer() {
  scriptName=$1
  uvicornBin=$(pwd)/.venv/bin/uvicorn
  cmdScript=$(pwd)/.venv/bin/$scriptName

  cat << BIN_SCRIPT > $cmdScript
#!/bin/sh

exec $uvicornBin \
  --reload-dir schoolLib \
  --reload-include '*.yaml' \
  --reload schoolLib.app.main:app

BIN_SCRIPT

  chmod a+x $cmdScript
}

installScript() {
  scriptName=$1
  cmdScript=$(pwd)/.venv/bin/$scriptName
  cat << CMD_SCRIPT > $HOME/.local/bin/$scriptName
#!/bin/sh

# This shell script was created by the simple-school-library tool
#       './scripts/installEditableSchoolLib'
# script.

exec $cmdScript \$@
CMD_SCRIPT

  chmod a+x $HOME/.local/bin/$scriptName
}

##########################################################################

createWebServer schoolLib
installScript schoolLib

installScript slReindex

installScript slPassword

installScript slUpdateDatabase

installScript slDump

installScript slRestore

installScript slSaveHelpPages

installScript slLoadHelpPages

echo ""
echo "The editable school library command have been created"
echo ""
