
import os
import sys
# import yaml

from schoolLib.app.main import setupApp
from schoolLib.setup.router import pageParts, \
  computePagePartUsers, routes

def runSanityChecks() :
  print("Running sanity tests")

  os.makedirs("tests/autoGenerated", exist_ok=True)

  setupApp()
  computePagePartUsers()

  for aPagePartName, aPagePart in pageParts.items():
    testName = aPagePartName.replace('.', '_')
    print(f"\n{aPagePartName}")
    for someMetaData in aPagePart.metaData :
      hxGet = someMetaData['hxGet']
      if hxGet :
        hxGetPrefix = hxGet
        if '{' in hxGet :
          hxGetPrefix = hxGet.split('{')[0].rstrip('/')
        hxGetName = hxGetPrefix.replace('/', '_')
        print(f"   hxGet: {hxGet} {testName} {hxGetPrefix}")
      hxPost = someMetaData['hxPost']
      if hxPost :
        print(f"  hxPost: {hxPost}")

def generateTests() :
  with open("tests/autoGenerated/test_autoGenerated_example.py", "w") as tFile :  # noqa
    tFile.write("""
def test_autoGenerated_example() :
  assert True
    """)

  sys.exit(1)

