
import os
# import yaml

def generateTests() :
  print("Creating autoGenerated tests")
  os.makedirs("tests/autoGenerated", exist_ok=True)

  with open("tests/autoGenerated/test_autoGenerated_example.py", "w") as tFile :  # noqa
    tFile.write("""
def test_autoGenerated_example() :
  assert True
    """)

